apiVersion: v1
kind: Service
metadata:
  name: voicebridge-rtp
spec:
  selector:
    app: voicebridge
  ports:
    - name: rtp
      port: 40000
      targetPort: 40000
      protocol: UDP
  type: ClusterIP
