apiVersion: v1
kind: Service
metadata:
  name: voicebridge-https
spec:
  selector:
    app: voicebridge
  ports:
    - name: https
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
