apiVersion: v1
kind: Service
metadata:
  name: voicebridge-http
spec:
  selector:
    app: voicebridge
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
